import assert from 'node:assert/strict';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { chromium } from 'playwright';
import { startFixtureServer } from '../scripts/fixture-server.mjs';
import { startGatewayServer } from '../scripts/serve.mjs';
import { createCheckinService } from '../scripts/checkin-service.mjs';

const directory = await mkdtemp(join(tmpdir(), 'kn10-checkin-browser-'));
const fixture = await startFixtureServer();
const sent = [];
const service = createCheckinService({ directory, runner: async account => {
  sent.push(account.name);
  await new Promise(resolve => setTimeout(resolve, 50));
  return account.name === '过期账号' ? { status: 'expired', httpStatus: 401 } : { status: 'success', httpStatus: 200, reward: 1000 };
} });
const first = await service.saveAccount({ site: '模拟 New API', name: '正常账号', baseUrl: 'https://site.example', protocol: 'newapi', authMode: 'cookie', userId: '1', cookie: 'session=browser-test-only' });
await service.saveAccount({ site: '模拟 AnyRouter', name: '过期账号', baseUrl: 'https://other.example', protocol: 'legacy', authMode: 'bearer', token: 'browser-login-token' });
await service.saveAccount({ site: '模拟站点', name: '停用账号', baseUrl: 'https://disabled.example', protocol: 'newapi', authMode: 'cookie', userId: '3', cookie: 'session=disabled', enabled: false });
const app = await startGatewayServer({ backendUrl: fixture.url, host: '127.0.0.1', port: 0, distDir: resolve('dist'), management: true, checkinService: service });
const base = 'http://127.0.0.1:' + app.server.address().port;
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  async function confirmJob() {
    const accepted = page.waitForResponse(response => response.url().endsWith('/api/checkins/jobs') && response.request().method() === 'POST');
    await page.getByRole('button', { name: '确认签到', exact: true }).click();
    assert.equal((await accepted).status(), 202);
  }
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base + '/dashboard/checkins');
  await page.getByLabel('登录密码').fill('linear-demo');
  await page.getByRole('button', { name: '进入管理端' }).click();
  await page.getByRole('heading', { name: '每日签到', exact: true }).waitFor();
  await page.getByRole('heading', { name: '模拟 New API', exact: true }).waitFor();
  assert.equal(sent.length, 0);
  assert(!await page.locator('.checkins-page').innerText().then(text => text.includes('browser-test-only')));
  await page.getByRole('button', { name: '编辑签到 正常账号', exact: true }).click();
  assert.equal(await page.getByLabel('Cookie', { exact: true }).inputValue(), '');
  await page.getByLabel('账号名称', { exact: true }).fill('编辑后账号');
  await page.getByRole('button', { name: '保存账号', exact: true }).click();
  await page.getByText('编辑后账号', { exact: true }).waitFor();
  assert.equal((await service.snapshot()).accounts.find(account => account.id === first.id).hasCookie, true);
  await page.getByRole('button', { name: '批量签到', exact: true }).click();
  assert.equal(sent.length, 0);
  await confirmJob();
  await service.waitForIdle();
  await page.getByRole('button', { name: '刷新', exact: true }).click();
  await page.getByText('部分失败', { exact: true }).waitFor();
  assert.deepEqual(sent, ['编辑后账号', '过期账号']);
  assert.equal((await service.snapshot()).history.length, 2);
  assert((await page.locator('.checkins-page').innerText()).includes('原始额度'));
  await page.getByRole('button', { name: '重试失败', exact: true }).click();
  await confirmJob();
  await service.waitForIdle();
  assert.equal(sent.at(-1), '过期账号');
  assert.equal(sent.length, 3);
  await page.getByRole('button', { name: '刷新', exact: true }).click();
  await page.getByRole('button', { name: '执行记录', exact: true }).click();
  await page.locator('.checkin-history-row').first().waitFor();
  await page.waitForFunction(() => document.querySelectorAll('.checkin-history-row').length === 3);
  assert.equal(await page.locator('.checkin-history-row').count(), 3);
  await page.getByRole('button', { name: '签到账号', exact: true }).click();
  await page.getByRole('button', { name: '添加账号', exact: true }).click();
  await page.getByLabel('站点名称', { exact: true }).fill('新增模拟站');
  await page.getByLabel('账号名称', { exact: true }).fill('新增账号');
  await page.getByLabel('站点地址', { exact: true }).fill('https://added.example');
  await page.getByLabel('用户 ID', { exact: true }).fill('4');
  await page.getByLabel('Cookie', { exact: true }).fill('session=added-test-only');
  await page.getByRole('button', { name: '保存账号', exact: true }).click();
  await page.getByRole('heading', { name: '新增模拟站', exact: true }).waitFor();
  await page.getByRole('button', { name: '删除签到 新增账号', exact: true }).click();
  await page.getByRole('button', { name: '确认删除', exact: true }).click();
  await page.getByRole('heading', { name: '新增模拟站', exact: true }).waitFor({ state: 'hidden' });
  await mkdir('screenshots', { recursive: true });
  await page.screenshot({ path: 'screenshots/checkins-desktop.png', fullPage: true });
  await page.getByLabel('主题模式').selectOption('dark');
  await page.setViewportSize({ width: 375, height: 900 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.screenshot({ path: 'screenshots/checkins-mobile.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('PASS: isolated checkin page CRUD, no credential disclosure, explicit confirmation, per-account batch failures, retry, records, themes and mobile. No real sites called.');
} finally {
  await browser.close();
  await service.waitForIdle();
  await app.close();
  await fixture.close();
  await rm(directory, { recursive: true, force: true });
}
