import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.PREVIEW_URL || 'http://127.0.0.1:4320';
assert.match(base, /^http:\/\/127\.0\.0\.1:(4320|4321)$/);
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--no-proxy-server'] });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}/dashboard/providers`);
  await page.getByLabel('登录密码').fill('web-e2e-local-20261003');
  await page.getByRole('button', { name: '进入管理端' }).click();
  await page.getByRole('button', { name: '添加供应商', exact: true }).waitFor();
  const run = Date.now().toString(36);
  const keyResponse = await page.request.post(`${base}/api/keys`, { data: { name: `E2E protocol key ${run}` } });
  assert.equal(keyResponse.status(), 201);
  const key = await keyResponse.json();
  const headers = { Authorization: `Bearer ${key.key}` };
  const nodes = [];
  for (const protocol of ['responses', 'anthropic']) {
    const prefix = `e2e-${protocol}-${run}`;
    const name = `E2E ${protocol} ${run}`;
    await page.getByRole('button', { name: '添加供应商', exact: true }).click();
    await page.getByLabel('供应商协议').selectOption(protocol === 'anthropic' ? 'anthropic-compatible' : 'openai-compatible');
    if (protocol === 'responses') await page.getByLabel('OpenAI 接口').selectOption('responses');
    await page.getByLabel('供应商名称', { exact: true }).fill(name);
    await page.getByLabel('路由前缀', { exact: true }).fill(prefix);
    await page.getByLabel('接口地址', { exact: true }).fill(`http://127.0.0.1:20130/v1/${protocol === 'anthropic' ? 'messages' : 'responses'}`);
    await page.getByLabel('上游 API Key', { exact: true }).fill('e2e-upstream-key');
    await page.getByRole('button', { name: '保存供应商', exact: true }).click();
    await page.getByRole('dialog').waitFor({ state: 'hidden' });
    await page.getByRole('heading', { name, exact: true }).waitFor();
    const catalog = await (await page.request.get(`${base}/api/provider-nodes`)).json();
    const node = catalog.nodes.find(item => item.prefix === prefix); nodes.push(node);
    assert.equal(node.baseUrl, 'http://127.0.0.1:20130/v1');
    await page.request.post(`${base}/api/models/custom`, { data: { providerAlias: node.id, id: 'e2e-model', type: 'llm', enabled: true } });
    const completion = await page.request.post('http://127.0.0.1:20129/api/v1/chat/completions', { headers, data: { model: `${prefix}/e2e-model`, stream: false, messages: [{ role: 'user', content: 'Reply OK' }] } });
    assert.equal(completion.status(), 200, await completion.text());
    assert.equal((await completion.json()).choices[0].message.content, 'OK');
  }
  const [first, second] = nodes;
  await page.request.post(`${base}/api/models/custom`, { data: { providerAlias: first.id, id: 'fail-model', type: 'llm', enabled: true } });
  await page.goto(`${base}/dashboard/combos`);
  await page.getByRole('button', { name: '创建组合模型', exact: true }).click();
  const comboName = `e2e-fallback-${run}`;
  await page.getByLabel('下游模型名称', { exact: true }).fill(comboName);
  for (const model of [`${first.prefix}/fail-model`, `${second.prefix}/e2e-model`]) {
    await page.getByLabel('选择成员模型').selectOption(model);
    await page.getByRole('button', { name: '添加成员', exact: true }).click();
  }
  await page.getByRole('button', { name: '保存组合模型', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  const completion = await page.request.post('http://127.0.0.1:20129/api/v1/chat/completions', { headers, data: { model: comboName, stream: false, messages: [{ role: 'user', content: 'Reply OK' }] } });
  assert.equal(completion.status(), 200, await completion.text());
  assert.equal((await completion.json()).choices[0].message.content, 'OK');
  await page.getByRole('button', { name: `编辑组合 ${comboName}`, exact: true }).click();
  await page.getByLabel('调度方式').selectOption('round-robin');
  await page.getByRole('button', { name: `上移 ${second.prefix}/e2e-model`, exact: true }).click();
  await page.getByRole('button', { name: '保存组合模型', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  const settings = await (await page.request.get(`${base}/api/settings`)).json();
  assert.equal(settings.comboStrategies[comboName].fallbackStrategy, 'round-robin');
  const combos = (await (await page.request.get(`${base}/api/combos`)).json()).combos;
  const combo = combos.find(item => item.name === comboName);
  assert.equal(combo.models[0], `${second.prefix}/e2e-model`);
  await page.goto(`${base}/dashboard/models`);
  await page.getByRole('button', { name: '全部目录', exact: true }).click();
  await page.getByLabel('搜索模型', { exact: true }).fill(`${second.prefix}/e2e-model`);
  await page.getByRole('button', { name: `停用模型 ${second.prefix}/e2e-model`, exact: true }).click();
  await page.getByRole('button', { name: `启用模型 ${second.prefix}/e2e-model`, exact: true }).waitFor();
  const list = (await (await page.request.get('http://127.0.0.1:20129/api/v1/models', { headers })).json()).data;
  assert(!list.some(item => item.id === `${second.prefix}/e2e-model`));
  await page.getByRole('button', { name: `启用模型 ${second.prefix}/e2e-model`, exact: true }).click();
  await page.getByRole('button', { name: `停用模型 ${second.prefix}/e2e-model`, exact: true }).waitFor();
  const enabled = (await (await page.request.get('http://127.0.0.1:20129/api/v1/models', { headers })).json()).data;
  assert(enabled.some(item => item.id === `${second.prefix}/e2e-model`));
  await page.request.delete(`${base}/api/combos/${combo.id}`);
  for (const node of nodes) await page.request.delete(`${base}/api/provider-nodes/${node.id}`);
  await page.request.delete(`${base}/api/keys/${key.id}`);
  assert.deepEqual(errors, []);
  console.log('PASS real backend: Responses and Anthropic creation/routing, endpoint normalization, cross-provider fallback, reorder/round-robin save, downstream model disable/enable.');
} finally { await browser.close(); }
