import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.PREVIEW_URL || 'http://127.0.0.1:4320';
const backend = 'http://127.0.0.1:20129';
assert.match(base, /^http:\/\/127\.0\.0\.1:(4320|4321)$/);
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--no-proxy-server'] });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultNavigationTimeout(120000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}/dashboard/providers`);
  await page.getByLabel('登录密码').fill('web-e2e-local-20261003');
  await page.getByRole('button', { name: '进入管理端' }).click();
  await page.getByRole('button', { name: '添加供应商', exact: true }).waitFor();
  const before = await (await page.request.get(`${base}/api/providers`)).json();
  assert((before.connections || []).every(connection => connection.name.startsWith('E2E')), 'Isolated backend only');
  const run = Date.now().toString(36);
  const prefix = `e2e-${run}`;
  const name = `E2E ${run}`;
  await page.getByRole('button', { name: '添加供应商', exact: true }).click();
  await page.getByLabel('供应商协议', { exact: true }).selectOption('openai-compatible');
  await page.getByLabel('OpenAI 接口', { exact: true }).selectOption('chat');
  await page.getByLabel('供应商名称', { exact: true }).fill(name);
  await page.getByLabel('路由前缀', { exact: true }).fill(prefix);
  await page.getByLabel('接口地址', { exact: true }).fill('http://127.0.0.1:20130/v1');
  await page.getByLabel('上游 API Key', { exact: true }).fill('e2e-upstream-key');
  const createConnection = page.waitForResponse(response => response.url().endsWith('/api/providers') && response.request().method() === 'POST');
  await page.getByRole('button', { name: '保存供应商', exact: true }).click();
  const createdResponse = await createConnection;
  assert.equal(createdResponse.status(), 201, await createdResponse.text());
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('heading', { name, exact: true }).waitFor();
  await page.getByRole('button', { name: `测试 ${name}`, exact: true }).click();
  await page.getByRole('status').filter({ hasText: '测试通过' }).waitFor();
  const allNodes = (await (await page.request.get(`${base}/api/provider-nodes`)).json()).nodes;
  const node = allNodes.find(item => item.prefix === prefix);
  assert(node);

  await page.goto(`${base}/dashboard/models`);
  await page.getByRole('button', { name: '添加自定义模型', exact: true }).click();
  await page.getByRole('dialog').getByLabel('模型供应商', { exact: true }).selectOption(node.id);
  await page.getByLabel('上游模型 ID', { exact: true }).fill('e2e-model');
  await page.getByLabel('显示名称', { exact: true }).fill('E2E custom model');
  await page.getByLabel('上下文 Token', { exact: true }).fill('64000');
  await page.getByLabel('最大输出 Token', { exact: true }).fill('4096');
  await page.getByRole('button', { name: '保存模型', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByLabel('搜索模型', { exact: true }).fill(`${prefix}/e2e-model`);
  await page.getByRole('cell', { name: '64,000', exact: true }).waitFor();
  await page.getByRole('button', { name: `编辑模型 ${prefix}/e2e-model`, exact: true }).click();
  await page.getByLabel('上下文 Token', { exact: true }).fill('96000');
  await page.getByRole('button', { name: '保存模型', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.reload();
  await page.getByLabel('搜索模型', { exact: true }).fill(`${prefix}/e2e-model`);
  await page.getByRole('cell', { name: '96,000', exact: true }).waitFor();

  await page.goto(`${base}/dashboard/endpoint`);
  await page.getByRole('button', { name: '创建密钥', exact: true }).click();
  await page.getByLabel('密钥名称', { exact: true }).fill(`E2E key ${run}`);
  const keyResponse = page.waitForResponse(response => response.url().endsWith('/api/keys') && response.request().method() === 'POST');
  await page.getByRole('dialog').getByRole('button', { name: '创建密钥', exact: true }).click();
  const key = await (await keyResponse).json();
  assert(key.key);
  const headers = { Authorization: `Bearer ${key.key}` };
  const list = await page.request.get(`${backend}/api/v1/models`, { headers });
  assert.equal(list.status(), 200);
  const downstream = (await list.json()).data;
  const advertised = downstream.find(model => model.id === `${prefix}/e2e-model`);
  assert(advertised, 'Registered model must be advertised downstream');
  assert.equal(advertised.context_length, 96000);
  assert.equal(advertised.max_completion_tokens, 4096);

  await page.goto(`${base}/dashboard/combos`);
  await page.getByRole('button', { name: '创建组合模型', exact: true }).click();
  await page.getByLabel('下游模型名称', { exact: true }).fill(`e2e-combo-${run}`);
  await page.getByLabel('选择成员模型', { exact: true }).selectOption(`${prefix}/e2e-model`);
  await page.getByRole('button', { name: '添加成员', exact: true }).click();
  await page.getByRole('button', { name: '保存组合模型', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.reload();
  await page.getByRole('cell', { name: `e2e-combo-${run}`, exact: true }).waitFor();
  const chat = await page.request.post(`${backend}/api/v1/chat/completions`, { headers, data: { model: `e2e-combo-${run}`, messages: [{ role: 'user', content: 'Reply OK' }], stream: false } });
  assert.equal(chat.status(), 200, await chat.text());
  assert.equal((await chat.json()).choices[0].message.content, 'OK');
  const listed = (await (await page.request.get(`${backend}/api/v1/models`, { headers })).json()).data;
  assert(listed.some(model => model.id === `e2e-combo-${run}`));

  await page.goto(`${base}/dashboard/balances`);
  await page.getByRole('heading', { name: '余额与配额', exact: true }).waitFor();
  await page.getByRole('tab', { name: '供应商余额', exact: true }).click();
  await page.getByText('该供应商尚未提供可查询的余额数据。', { exact: true }).first().waitFor();
  await page.getByLabel(`查询余额 ${name}`, { exact: true }).click();
  await page.getByText('余额查询已关闭', { exact: true }).first().waitFor();
  await page.getByLabel(`查询余额 ${name}`, { exact: true }).click();
  await page.getByRole('button', { name: '刷新余额与配额', exact: true }).click();
  await mkdir('screenshots', { recursive: true });
  for (const route of ['providers', 'models', 'combos', 'balances', 'logs', 'monitor', 'overview', 'usage', 'endpoint']) {
    await page.goto(`${base}/dashboard/${route}`);
    await page.locator('h1').waitFor();
    for (const width of [1440, 375]) {
      await page.setViewportSize({ width, height: 1000 });
      await page.waitForTimeout(300);
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${route} overflow ${width}`);
    }
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${base}/dashboard/combos`);
  await page.getByRole('button', { name: `删除组合 e2e-combo-${run}`, exact: true }).click();
  await page.getByRole('button', { name: '确认删除', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.goto(`${base}/dashboard/providers/${node.id}`);
  await page.getByRole('button', { name: '删除供应商', exact: true }).click();
  await page.getByRole('button', { name: '确认删除', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal((await page.request.delete(`${base}/api/keys/${key.id}`)).status(), 200);
  assert.deepEqual(errors, []);
  console.log('PASS real isolated backend: provider + key creation/test, custom model and context persistence, downstream models + caps, combo routing, balance preferences, all nine pages desktop/mobile, delete cleanup.');
} finally { await browser.close(); }
